version: '3.4'

services:
  react-next-sid:
    image: react-next-sid
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    # command: ["tail", "-f", "/dev/null"]