name: Build
on:
  push:
    branches:
      # - main
      - sid-fix

# env:
#   PUBLIC_URL: ${{ vars.PUBLIC_URL }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # submodules: true
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - run: git submodule update --init --recursive --remote
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn
      - run: yarn run build

      - run: yarn run lint
      # - run: "yarn run test:unit"
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: code-coverage
      #     path: coverage
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker Image and Push to GHCR
        uses: GlueOps/github-actions-build-push-containers@0.4.0
    